server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: product-ventas-route # Nueva ruta para el mismo servicio
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/ventas/**
 # NUEVA RUTA para el Banco (Agrega esto aquí)
        - id: banco-bci-route
          uri: lb://BANCO-BCI
          predicates:
            - Path=/registro/**