server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ # <- ¡Esto salva al Gateway!

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: product-ventas-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/ventas/**
        - id: banco-bci-route
          uri: lb://banco-bci
          predicates:
            - Path=/consulta/**, /registro/**

# Opcional pero recomendado para ver qué falla
logging:
  level:
    org.springframework.cloud.gateway: INFO
