server:
  port: 8083  # El puerto donde corre en la Máquina 2

spring:
  application:
    name: banco-bci  # ESTO es lo que Eureka leerá para registrarlo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.37.213:8761/eureka/
  instance:
    # Esto le dice a Eureka qué puerto informar a los demás
    nonSecurePort: 8083
    preferIpAddress: true
