server:
  port: 8082  # El puerto donde corre en la Máquina 2

spring:
  application:
    name: banco-bci  # ESTO es lo que Eureka leerá para registrarlo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.37.213:8761/eureka/
  instance:
    prefer-ip-address: true # Para que Eureka use la IP y no el nombre del contenedor

